apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app2

spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
     labels: 
       app: flask-hello
    spec:
      containers:
        - name: flask-app-teja
          image: viswabhanu/tejawithdata:1
          ports:
            - containerPort: 9999
    