apiVersion: v1  
kind: ReplicationController
metadata:
  name: replication
  labels:
    app: myApp
    type: flask_app
spec:
  template:
    metadata:
      name: flask
      labels:
        env: production
    spec: 
      containers:
        - name: Teja
          image: viswabhanu/tejawithdata
  replicas: 2