apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  ports:
    - name: load-flask
      protocol: TCP
      port: 9999
      targetPort: 9999
  selector:
   app: flask-hello
